# Generated by Django 3.0.5 on 2020-05-02 15:17

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200430_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
