# Generated by Django 3.0.5 on 2020-05-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200502_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
