# Generated by Django 3.0.5 on 2020-05-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='area',
            new_name='region',
        ),
    ]
